version: "1"
capabilities:
    - contract_id: abesh:httpserver2
      values:
        default_404_handler_enabled: "true"
        default_content_type: application/json
        default_request_timeout: 5s
        host: 0.0.0.0
        port: "8080"
        s403m: |
            {
                "status_code": "SE_403",
                "error_code": 9999,
                "error_prefix": "SE_403",
                "detail": "403 ERROR"
            }
        s404m: |
            {
                "status_code": "SE_404",
                "error_code": 9999,
                "error_prefix": "SE_404",
                "detail": "404 ERROR"
            }
        s405m: |
            {
                "status_code": "SE_405",
                "error_code": 9999,
                "error_prefix": "SE_405",
                "detail": "405 ERROR"
            }
        s408m: |
            {
                "status_code": "SE_408",
                "error_code": 9999,
                "error_prefix": "SE_408",
                "detail": "408 ERROR"
            }
        s499m: |
            {
                "status_code": "SE_499",
                "error_code": 9999,
                "error_prefix": "SE_499",
                "detail": "499 ERROR"
            }
        s500m: |
            {
                "status_code": "SE_500",
                "error_code": 9999,
                "error_prefix": "SE_500",
                "detail": "500 ERROR"
            }
    - contract_id: abesh:health
    - contract_id: abesh:echo
triggers:
    - trigger: abesh:httpserver2
      trigger_values:
        method: GET
        path: /_abesh/v1/health
      service: abesh:health
    - trigger: abesh:httpserver2
      trigger_values:
        method: GET
        path: /echo
      service: abesh:echo
start:
    - abesh:httpserver2
