// Generated By Abesh CLI At: Sunday, 05-Jun-22 19:09:35 +06
// TODO: EDIT THIS FILE AND IMPLEMENT YOUR SERVICE

package echo

import "github.com/mkawserm/abesh/constant"

// Category of the service
const Category = string(constant.CategoryService)
