// Generated By Abesh CLI At: Sunday, 05-Jun-22 19:09:35 +06
// TODO: EDIT THIS FILE AND IMPLEMENT YOUR SERVICE

package echo

import (
	"context"

	"github.com/mkawserm/abesh/iface"
	"github.com/mkawserm/abesh/model"
	"github.com/mkawserm/abesh/registry"

	"github.com/amjadjibon/example/constant"
)

type Echo struct {
	mCM model.ConfigMap
}

func (e *Echo) Name() string {
	return Name
}

func (e *Echo) Version() string {
	return constant.Version
}

func (e *Echo) Category() string {
	return Category
}

func (e *Echo) ContractId() string {
	return ContractId
}

func (e *Echo) GetConfigMap() model.ConfigMap {
	return e.mCM
}

func (e *Echo) SetConfigMap(cm model.ConfigMap) error {
	e.mCM = cm
	return nil
}

func (e *Echo) Setup() error {
	return nil
}

func (e *Echo) New() iface.ICapability {
	return &Echo{}
}

func (e *Echo) Serve(ctx context.Context, event *model.Event) (*model.Event, error) {
	return model.GenerateOutputEvent(
		event.Metadata,
		e.ContractId(),
		"OK",
		200,
		"application/json",
		[]byte("{}"),
	), nil
}

func init() {
	registry.GlobalRegistry().AddCapability(&Echo{})
}
